// Barrel re-export — todos os hooks estão organizados por domínio em hooks/api/
export * from './api/auth'
export * from './api/patients'
export * from './api/appointments'
export * from './api/sessions'
export * from './api/financial'
export * from './api/availability'
export * from './api/booking'
export * from './api/notifications'
export * from './api/templates'
export * from './api/documents'
export * from './api/instruments'
export * from './api/testimonial'
export * from './api/admin'
export * from './api/churn'
export * from './api/dashboard'
