import { Prontuario, Documento } from '@/types/prontuario'

export const mockProntuarios: Record<string, Prontuario> = {
  '1': {
    id: 'p1',
    patientId: '1',
    queixaPrincipal: 'Ansiedade generalizada, dificuldades em situações sociais e insônia recorrente.',
    historicoDoenca: 'Sintomas presentes há aproximadamente 3 anos, com piora após mudança de emprego em 2022.',
    antecedentesPessoais: 'Episódio depressivo leve em 2019, sem hospitalização. Acompanhamento psiquiátrico por 6 meses.',
    historicoFamiliar: 'Mãe com transtorno de ansiedade, pai com histórico de depressão.',
    medicamentos: 'Escitalopram 10mg (prescrito pela psiquiatra Dra. Renata Souza, CRM 12345).',
    condicoesMedicas: 'Hipotireoidismo controlado.',
    abordagem: 'Terapia Cognitivo-Comportamental (TCC)',
    objetivos: 'Reduzir sintomas ansiosos, desenvolver habilidades sociais, melhorar qualidade do sono e autoestima.',
    frequencia: 'Semanal (50 minutos)',
    duracaoPrevista: '12 a 18 meses',
    contatoEmergenciaNome: 'Beatriz Santos (mãe)',
    contatoEmergenciaPhone: '(11) 98888-1111',
    contatoEmergenciaRelacao: 'Mãe',
    escolaridade: 'Superior completo',
    profissao: 'Designer',
    estadoCivil: 'Solteira',
    religiao: 'Sem religião',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  '2': {
    id: 'p2',
    patientId: '2',
    queixaPrincipal: 'Burnout, desmotivação profissional e dificuldades no relacionamento conjugal.',
    historicoDoenca: 'Quadro de esgotamento há 18 meses, intensificado após promoção com aumento de responsabilidades.',
    antecedentesPessoais: 'Sem histórico psiquiátrico anterior.',
    historicoFamiliar: 'Irmão com diagnóstico de TDAH.',
    medicamentos: 'Nenhum.',
    condicoesMedicas: 'Nenhuma.',
    abordagem: 'Terapia Analítica e Psicoterapia Focada na Emoção (EFT)',
    objetivos: 'Ressignificar relação com trabalho, fortalecer vínculos afetivos, desenvolver autocuidado.',
    frequencia: 'Semanal (50 minutos)',
    duracaoPrevista: '12 meses',
    contatoEmergenciaNome: 'Fernanda Lima (esposa)',
    contatoEmergenciaPhone: '(11) 97777-2222',
    contatoEmergenciaRelacao: 'Cônjuge',
    escolaridade: 'Pós-graduação',
    profissao: 'Gerente de TI',
    estadoCivil: 'Casado',
    religiao: 'Católico',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: new Date().toISOString(),
  },
}

const now = new Date()
const fmt = (d: Date) => d.toLocaleDateString('pt-BR')

export const mockDocumentos: Documento[] = [
  {
    id: 'd1',
    patientId: '1',
    patientName: 'Ana Beatriz Santos',
    type: 'declaracao',
    title: 'Declaração de Comparecimento — Ana Beatriz Santos',
    content: `Declaro, para os devidos fins, que Ana Beatriz Santos compareceu a 8 (oito) sessões de psicoterapia no período de 01/01/2026 a ${fmt(now)}, sob minha responsabilidade profissional.`,
    signedAt: now.toISOString(),
    signCode: 'PS-2026-A1B2C3D4',
    crp: '06/123456',
    psychologistName: 'Dra. Camila Moura',
    createdAt: now.toISOString(),
  },
  {
    id: 'd2',
    patientId: '2',
    patientName: 'Carlos Eduardo Lima',
    type: 'recibo',
    title: 'Recibo — Carlos Eduardo Lima',
    content: `Recebi de Carlos Eduardo Lima a quantia de R$ 200,00 (duzentos reais) referente à sessão de psicoterapia realizada em ${fmt(now)}.`,
    signedAt: now.toISOString(),
    signCode: 'PS-2026-E5F6G7H8',
    crp: '06/123456',
    psychologistName: 'Dra. Camila Moura',
    createdAt: now.toISOString(),
  },
]
