import { Patient, Appointment, Session, FinancialRecord, DashboardStats } from '@/types'

export const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'Ana Beatriz Santos',
    email: 'ana@email.com',
    phone: '(11) 99999-1111',
    birthDate: '1990-05-15',
    pronouns: 'ela/dela',
    tags: ['ansiedade', 'autoestima'],
    status: 'active',
    sessionPrice: 180,
    sessionDuration: 50,
    startDate: '2024-03-01',
    avatarColor: 'bg-sage-200 text-sage-700',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Carlos Eduardo Lima',
    email: 'carlos@email.com',
    phone: '(11) 99999-2222',
    birthDate: '1985-11-22',
    pronouns: 'ele/dele',
    tags: ['depressao', 'trabalho'],
    status: 'active',
    sessionPrice: 200,
    sessionDuration: 50,
    startDate: '2024-01-15',
    avatarColor: 'bg-mist-200 text-mist-700',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    name: 'Mariana Ferreira',
    email: 'mariana@email.com',
    phone: '(11) 99999-3333',
    birthDate: '1995-08-03',
    pronouns: 'ela/dela',
    tags: ['luto', 'familia'],
    status: 'active',
    sessionPrice: 150,
    sessionDuration: 60,
    startDate: '2024-06-10',
    avatarColor: 'bg-warm-200 text-warm-700',
    createdAt: '2024-06-10T10:00:00Z',
    updatedAt: '2024-06-10T10:00:00Z',
  },
  {
    id: '4',
    name: 'Pedro Alves Costa',
    email: 'pedro@email.com',
    phone: '(11) 99999-4444',
    birthDate: '1978-02-14',
    pronouns: 'ele/dele',
    tags: ['relacionamento', 'progresso'],
    status: 'active',
    sessionPrice: 220,
    sessionDuration: 50,
    startDate: '2023-11-05',
    avatarColor: 'bg-purple-200 text-purple-700',
    createdAt: '2023-11-05T10:00:00Z',
    updatedAt: '2023-11-05T10:00:00Z',
  },
  {
    id: '5',
    name: 'Sofia Rodrigues',
    email: 'sofia@email.com',
    phone: '(11) 99999-5555',
    birthDate: '2000-12-30',
    pronouns: 'ela/dela',
    tags: ['identidade', 'ansiedade'],
    status: 'paused',
    sessionPrice: 160,
    sessionDuration: 50,
    startDate: '2024-02-20',
    avatarColor: 'bg-pink-200 text-pink-700',
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
  },
]

const today = new Date()
const todayStr = today.toISOString().split('T')[0]
const tomorrow = new Date(today)
tomorrow.setDate(today.getDate() + 1)
const tomorrowStr = tomorrow.toISOString().split('T')[0]

export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    patientId: '1',
    patient: mockPatients[0],
    date: todayStr,
    time: '09:00',
    duration: 50,
    status: 'scheduled',
    modality: 'presencial',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'a2',
    patientId: '2',
    patient: mockPatients[1],
    date: todayStr,
    time: '10:00',
    duration: 50,
    status: 'scheduled',
    modality: 'online',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'a3',
    patientId: '3',
    patient: mockPatients[2],
    date: todayStr,
    time: '14:00',
    duration: 60,
    status: 'completed',
    modality: 'presencial',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'a4',
    patientId: '4',
    patient: mockPatients[3],
    date: tomorrowStr,
    time: '09:30',
    duration: 50,
    status: 'scheduled',
    modality: 'online',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'a5',
    patientId: '5',
    patient: mockPatients[4],
    date: tomorrowStr,
    time: '11:00',
    duration: 50,
    status: 'scheduled',
    modality: 'presencial',
    createdAt: new Date().toISOString(),
  },
]

export const mockSessions: Session[] = [
  {
    id: 's1',
    patientId: '1',
    patient: mockPatients[0],
    appointmentId: 'a3',
    date: todayStr,
    duration: 50,
    mood: 4,
    summary: 'Pessoa relatou melhora significativa em situações sociais. Trabalhamos técnicas de respiração.',
    tags: ['ansiedade', 'progresso'],
    paymentStatus: 'paid',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 's2',
    patientId: '2',
    patient: mockPatients[1],
    date: new Date(today.setDate(today.getDate() - 7)).toISOString().split('T')[0],
    duration: 50,
    mood: 2,
    summary: 'Sessão focada em gestão de estresse no ambiente de trabalho.',
    tags: ['trabalho', 'depressao'],
    paymentStatus: 'pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockFinancial: FinancialRecord[] = [
  {
    id: 'f1',
    patientId: '1',
    patient: mockPatients[0],
    sessionId: 's1',
    type: 'income',
    amount: 180,
    description: 'Sessão - Ana Beatriz Santos',
    status: 'paid',
    paidAt: new Date().toISOString(),
    method: 'pix',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f2',
    patientId: '2',
    patient: mockPatients[1],
    sessionId: 's2',
    type: 'income',
    amount: 200,
    description: 'Sessão - Carlos Eduardo Lima',
    status: 'pending',
    dueDate: tomorrowStr,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f3',
    patientId: '3',
    patient: mockPatients[2],
    type: 'income',
    amount: 150,
    description: 'Sessão - Mariana Ferreira',
    status: 'paid',
    paidAt: new Date().toISOString(),
    method: 'credit_card',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f4',
    patientId: '4',
    patient: mockPatients[3],
    type: 'income',
    amount: 220,
    description: 'Sessão - Pedro Alves Costa',
    status: 'overdue',
    dueDate: '2024-12-01',
    createdAt: new Date().toISOString(),
  },
]

export const mockDashboard: DashboardStats = {
  sessionsThisWeek: 8,
  sessionsThisMonth: 32,
  activePatients: 4,
  pendingPayments: 2,
  pendingAmount: 420,
  monthRevenue: 4680,
  nextAppointment: mockAppointments[0],
}
